# Generated by Django 4.1.7 on 2023-02-16 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_education_city_education_date_started_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='feature_image',
            field=models.ImageField(blank=True, null=True, upload_to='publication_pics'),
        ),
    ]
