# Generated by Django 4.1.7 on 2023-02-20 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_publication_feature_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='doi',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='publication',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
    ]
