# Generated by Django 4.1.7 on 2023-02-20 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_alter_education_award_alter_education_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='award',
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='education',
            name='course',
            field=models.CharField(max_length=5000),
        ),
    ]
